on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PASS}}

      - name: build and push
        run: |
          docker build . -t tomasstorc/image-test:latest
          docker push tomasstorc/image-test:latest
